# Generated by Django 4.2 on 2024-02-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_verdict_action_alter_verdict_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending'),
        ),
    ]
