# Generated by Django 4.2 on 2024-02-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='security_key',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
