# Generated by Django 4.2 on 2024-03-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_transaction_security_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.TextField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')]),
        ),
    ]
